name: Test and Deploy

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3 
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Test with pytest
        run: |
          pipenv run pytest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      # For exoframe we need NodeJS
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # We install exoframe
      - name: Install exoframe
        run: npm install -g exoframe

      # And deploy using our secret token
      - name: Deploy to production
        run: |
          exoframe deploy --token ${{ secrets.EXOFRAME_TOKEN }} --endpoint "https://exoframe.xf.mkrs.link" --update
